id: P009259
initial_creation_type: ocr
source_metadata:
  id: bdr:W29219
  title: ཁྲི་ལོ་ཉེར་ལྔའི་མཛད་རྗེས་དྲན་དེབ།
  author: ''
  volumes:
    f02665f786d6487c997d3b1bb841e3d3:
      image_group_id: I1KG18464
      title: ''
      volume_number: 1
      total_pages: 158
